# Deployment do conversor
apiVersion: apps/v1
kind: Deployment
metadata:
  # Nome da minha aplicação
  name: conversor
  # Especificações
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
      - name: conversao-temperatura
        image: ricardomenck/conversao-temperatura:latest
        ports:
        - containerPort: 8080

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: conversor
spec:
  selector:
    app: conversor
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort